Client:
    type: entity
    table: client
    uniqueConstraints:
        client_username_key:
            columns:
                - username
        client_email_key:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        lastName:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
            column: last_name
        firstName:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
            column: first_name
        username:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
